trainingInput:
  hyperparameters:
    goal: MINIMIZE
    maxTrials: 60
    maxParallelTrials: 1
    hyperparameterMetricTag: epoch_val_loss
    enableTrialEarlyStopping: True
    params:
    - parameterName: num_dense_layers
      type: DISCRETE
      discreteValues:
      - 1
      - 2
      - 3
      - 4
      - 5
    - parameterName: neurons
      type: DISCRETE
      discreteValues:
      - 16
      - 32
      - 64
      - 128
      - 256
      - 512
    - parameterName: batch_size
      type: DISCRETE
      discreteValues:
      - 128
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.0001
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
    - parameterName: dropout
      type: DOUBLE
      minValue: 0.0
      maxValue: 0.8
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: embedding_dropout
      type: DOUBLE
      minValue: 0.0
      maxValue: 0.8
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: embed_dim
      type: INTEGER
      minValue: 3
      maxValue: 15
      scaleType: UNIT_LINEAR_SCALE
      
